flashcards/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.deck_list, name='deck_list'),
    path('deck/<int:deck_id>/flashcard', views.flash_card, name='flash_card'),
]

flashcards/flashcards/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + debug_toolbar_urls()

flashcards/core/models.py
from django.db import models

from .managers import CardManager


class Deck(models.Model):
    name = models.CharField(max_length=50)
    last_studied = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Card(models.Model):
    deck_id = models.ForeignKey(Deck, on_delete=models.CASCADE)
    front = models.CharField(max_length=100)
    back = models.CharField(max_length=100)
    last_review_date = models.DateTimeField(null=True, blank=True)
    next_review_date = models.DateTimeField(null=True, blank=True)

    objects = CardManager()

    def __str__(self):
        return f"{self.front} - {self.back}"

flashcards/core/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .models import Deck, Card
from .srs.simple_srs import SimpleSRS


def deck_list(request):
    decks = Deck.objects.all()
    return render(request, "core/decks.html", {"decks": decks})


def flash_card(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    current_date = timezone.now()

    if request.method == "POST":
        deck.last_studied = current_date
        deck.save()

        card_id = request.POST.get("card_id")
        feedback = request.POST.get("feedback")
        srs = SimpleSRS()
        next_review_date = srs.calculate_next_review_date(today=current_date, feedback=feedback)
        card = Card.objects.get(pk=card_id)
        card.last_review_date = current_date
        card.next_review_date = next_review_date
        card.save()

    card = Card.objects.next_card(current_date=current_date, deck=deck)
    return render(request,
                  "core/flash_card.html",
                  {"deck_name": deck.name, "card": card})

flashcards/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/core.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm fixed-top bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'deck_list' %}">Flash Cards</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'deck_list' %}">My Decks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-4 main-content">
        {% block content %}{% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

flashcards/core/templates/core/decks.html
{% extends "base.html" %}

{% block title %}My decks{% endblock %}

{% block content %}
<h1 class="mb-4">My decks</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of cards</th>
            <th>Last time studied</th>
        </tr>
    </thead>
    <tbody>
        {% for deck in decks %}
        <tr>
            <td>
                <a href="{% url 'flash_card' deck.id %}">{{ deck.name }}</a>
            </td>
            <td>{{ deck.card_set.count }}</td>
            <td>{{ deck.last_studied|date:"Y-m-d H:i"|default:"never used" }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3" class="text-center fst-italic">No decks available.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

flashcards/core/templates/core/flash_card.html
{% extends "base.html" %}
{% load static %}

{% block title %}Studying: {{ deck_name }}{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'core/css/flash_card.css' %}">
{% endblock %}

{% block content %}
<h1 class="mb-4">Studying: {{ deck_name }}</h1>

{% if card is not None %}
<div class="d-flex flex-column align-items-center">
    <form method="post" class="text-center">
        {% csrf_token %}

        <div class="flash-card mb-3">
            <div class="card-front">
                <p>{{ card.front }}</p>
                <small class="text-body-secondary fst-italic">(Click to flip)</small>
            </div>
            <div class="card-back">
                <p>{{ card.back }}</p>
            </div>
        </div>

        <div class="feedback-buttons mt-4">
            <p>How did you do?</p>
            <button type="submit" name="feedback" value="again" class="btn btn-lg btn-outline-danger mx-1">Again</button>
            <button type="submit" name="feedback" value="hard" class="btn btn-lg btn-outline-warning mx-1">Hard</button>
            <button type="submit" name="feedback" value="good" class="btn btn-lg btn-outline-success mx-1">Good</button>
            <button type="submit" name="feedback" value="easy" class="btn btn-lg btn-outline-info mx-1">Easy</button>
            <input type="hidden" name="card_id" value="{{ card.id }}" />
        </div>
    </form>
</div>
{% else %}
<div class="alert alert-success text-center" role="alert">
    No more cards in this deck. Please, go back later.
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{% static 'core/js/flash_card.js' %}" defer></script>
{% endblock %}